#!/bin/ash
PUID=${PUID:-1000}
PGID=${PGID:-1000}

mkdir -p /config/db
mkdir -p /config/artwork
mkdir -p /series
mkdir -p /movies
mkdir -p /transcode

if id -u $PUID > /dev/null 2>&1 && id -g $PGID > /dev/null 2>&1; then
    chown $PUID:$PGID /config
    chown $PUID:$PGID /movies
    chown $PUID:$PGID /series
    chown $PUID:$PGID /transcode
    su -m $PUID -c 'python src/init_db.py'
else
    python src/init_db.py
fi

touch /config/restart.txt
touch /config/shutdown.txt

last_restart_modified=$(stat -c %Y /config/restart.txt)
last_shutdown_modified=$(stat -c %Y /config/shutdown.txt)

while true; do
    APP_PORT=$(python -c 'from startup.get_port import get_port; print(get_port())')

    if id -u $PUID > /dev/null 2>&1 && id -g $PGID > /dev/null 2>&1; then
        su -m $PUID -c 'uvicorn src.main:app --host 0.0.0.0 --port '"$APP_PORT" &
    else
        uvicorn src.main:app --host 0.0.0.0 --port $APP_PORT &
    fi

    uvicorn_pid=$!

    while true; do
        sleep 1
        new_restart_modified=$(stat -c %Y /config/restart.txt)
        new_shutdown_modified=$(stat -c %Y /config/shutdown.txt)
        if [ "$new_restart_modified" != "$last_restart_modified" ]; then
            last_restart_modified=$new_restart_modified
            kill $uvicorn_pid
            wait $uvicorn_pid
            break
        elif [ "$new_shutdown_modified" != "$last_shutdown_modified" ]; then
            kill $uvicorn_pid
            wait $uvicorn_pid
            exit 0
        fi
    done
done