from sqlalchemy import insert
from src.models.profile import Profile


def seed_profiles(conn):
    for profile in default_profiles:
        conn.execute(insert(Profile).values(profile))


default_profiles = [
    {
        "name": "Any",
        "container": "matroska",
        "extension": "mkv",
        "pass_thru_common_metadata": True,
        "flipping": False,
        "rotation": 0,
        "cropping": "automatic",
        "limit": "none",
        "anamorphic": "automatic",
        "fill": "none",
        "color": "black",
        "detelecine": "default",
        "interlace_detection": "default",
        "deinterlace": "decomb",
        "deinterlace_preset": "default",
        "deblock": "off",
        "deblock_tune": "medium",
        "denoise": "off",
        "denoise_preset": "light",
        "denoise_tune": "none",
        "chroma_smooth": "off",
        "chroma_smooth_tune": "none",
        "sharpen": "off",
        "sharpen_preset": "medium",
        "colorspace": "off",
        "grayscale": False,
        "codec": "Any",
        "encoder": "",
        "framerate": "same as source",
        "framerate_type": "peak framerate",
        "quality_type": "constant quality",
        "constant_quality": 22,
        "average_bitrate": 15000,
        "multipass_encoding": False,
        "preset": "medium",
        "tune": "none",
        "profile": "auto",
        "level": "auto",
        "fast_decode": False
    },
    {
        "name": "h264",
        "container": "matroska",
        "extension": "mkv",
        "pass_thru_common_metadata": True,
        "flipping": False,
        "rotation": 0,
        "cropping": "automatic",
        "limit": "none",
        "anamorphic": "automatic",
        "fill": "none",
        "color": "black",
        "detelecine": "default",
        "interlace_detection": "default",
        "deinterlace": "decomb",
        "deinterlace_preset": "default",
        "deblock": "off",
        "deblock_tune": "medium",
        "denoise": "off",
        "denoise_preset": "light",
        "denoise_tune": "none",
        "chroma_smooth": "off",
        "chroma_smooth_tune": "none",
        "sharpen": "off",
        "sharpen_preset": "medium",
        "colorspace": "off",
        "grayscale": False,
        "codec": "h264",
        "encoder": "libx264",
        "framerate": "same as source",
        "framerate_type": "peak framerate",
        "quality_type": "constant quality",
        "constant_quality": 22,
        "average_bitrate": 15000,
        "multipass_encoding": False,
        "preset": "medium",
        "tune": "none",
        "profile": "auto",
        "level": "auto",
        "fast_decode": False
    },
    {
        "name": "hevc",
        "container": "matroska",
        "extension": "mkv",
        "pass_thru_common_metadata": True,
        "flipping": False,
        "rotation": 0,
        "cropping": "automatic",
        "limit": "none",
        "anamorphic": "automatic",
        "fill": "none",
        "color": "black",
        "detelecine": "default",
        "interlace_detection": "default",
        "deinterlace": "decomb",
        "deinterlace_preset": "default",
        "deblock": "off",
        "deblock_tune": "medium",
        "denoise": "off",
        "denoise_preset": "light",
        "denoise_tune": "none",
        "chroma_smooth": "off",
        "chroma_smooth_tune": "none",
        "sharpen": "off",
        "sharpen_preset": "medium",
        "colorspace": "off",
        "grayscale": False,
        "codec": "hevc",
        "encoder": "libx265",
        "framerate": "same as source",
        "framerate_type": "peak framerate",
        "quality_type": "constant quality",
        "constant_quality": 22,
        "average_bitrate": 15000,
        "multipass_encoding": False,
        "preset": "medium",
        "tune": "none",
        "profile": "auto",
        "level": "auto",
        "fast_decode": False
    },
    {
        "name": "mpeg4",
        "container": "matroska",
        "extension": "mkv",
        "pass_thru_common_metadata": True,
        "flipping": False,
        "rotation": 0,
        "cropping": "automatic",
        "limit": "none",
        "anamorphic": "automatic",
        "fill": "none",
        "color": "black",
        "detelecine": "default",
        "interlace_detection": "default",
        "deinterlace": "decomb",
        "deinterlace_preset": "default",
        "deblock": "off",
        "deblock_tune": "medium",
        "denoise": "off",
        "denoise_preset": "light",
        "denoise_tune": "none",
        "chroma_smooth": "off",
        "chroma_smooth_tune": "none",
        "sharpen": "off",
        "sharpen_preset": "medium",
        "colorspace": "off",
        "grayscale": False,
        "codec": "mpeg4",
        "encoder": "mpeg4",
        "framerate": "same as source",
        "framerate_type": "peak framerate",
        "quality_type": "constant quality",
        "constant_quality": 22,
        "average_bitrate": 15000,
        "multipass_encoding": False,
        "preset": "",
        "tune": "",
        "profile": "",
        "level": "",
        "fast_decode": False
    },
    {
        "name": "vp8",
        "container": "matroska",
        "extension": "mkv",
        "pass_thru_common_metadata": True,
        "flipping": False,
        "rotation": 0,
        "cropping": "automatic",
        "limit": "none",
        "anamorphic": "automatic",
        "fill": "none",
        "color": "black",
        "detelecine": "default",
        "interlace_detection": "default",
        "deinterlace": "decomb",
        "deinterlace_preset": "default",
        "deblock": "off",
        "deblock_tune": "medium",
        "denoise": "off",
        "denoise_preset": "light",
        "denoise_tune": "none",
        "chroma_smooth": "off",
        "chroma_smooth_tune": "none",
        "sharpen": "off",
        "sharpen_preset": "medium",
        "colorspace": "off",
        "grayscale": False,
        "codec": "vp8",
        "encoder": "libvpx-vp8",
        "framerate": "same as source",
        "framerate_type": "peak framerate",
        "quality_type": "constant quality",
        "constant_quality": 22,
        "average_bitrate": 15000,
        "multipass_encoding": False,
        "preset": "medium",
        "tune": "none",
        "profile": "auto",
        "level": "auto",
        "fast_decode": False
    },
    {
        "name": "vp9",
        "container": "matroska",
        "extension": "mkv",
        "pass_thru_common_metadata": True,
        "flipping": False,
        "rotation": 0,
        "cropping": "automatic",
        "limit": "none",
        "anamorphic": "automatic",
        "fill": "none",
        "color": "black",
        "detelecine": "default",
        "interlace_detection": "default",
        "deinterlace": "decomb",
        "deinterlace_preset": "default",
        "deblock": "off",
        "deblock_tune": "medium",
        "denoise": "off",
        "denoise_preset": "light",
        "denoise_tune": "none",
        "chroma_smooth": "off",
        "chroma_smooth_tune": "none",
        "sharpen": "off",
        "sharpen_preset": "medium",
        "colorspace": "off",
        "grayscale": False,
        "codec": "vp9",
        "encoder": "libvpx-vp9",
        "framerate": "same as source",
        "framerate_type": "peak framerate",
        "quality_type": "constant quality",
        "constant_quality": 22,
        "average_bitrate": 15000,
        "multipass_encoding": False,
        "preset": "medium",
        "tune": "none",
        "profile": "auto",
        "level": "auto",
        "fast_decode": False
    },
    {
        "name": "av1",
        "container": "matroska",
        "extension": "mkv",
        "pass_thru_common_metadata": True,
        "flipping": False,
        "rotation": 0,
        "cropping": "automatic",
        "limit": "none",
        "anamorphic": "automatic",
        "fill": "none",
        "color": "black",
        "detelecine": "default",
        "interlace_detection": "default",
        "deinterlace": "decomb",
        "deinterlace_preset": "default",
        "deblock": "off",
        "deblock_tune": "medium",
        "denoise": "off",
        "denoise_preset": "light",
        "denoise_tune": "none",
        "chroma_smooth": "off",
        "chroma_smooth_tune": "none",
        "sharpen": "off",
        "sharpen_preset": "medium",
        "colorspace": "off",
        "grayscale": False,
        "codec": "av1",
        "encoder": "libaom-av1",
        "framerate": "same as source",
        "framerate_type": "peak framerate",
        "quality_type": "constant quality",
        "constant_quality": 22,
        "average_bitrate": 15000,
        "multipass_encoding": False,
        "preset": "medium",
        "tune": "none",
        "profile": "auto",
        "level": "auto",
        "fast_decode": False
    },
]
